package com.srijonashraf.atm;
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.Color;
import javax.swing.border.LineBorder;
import javax.swing.plaf.ButtonUI;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.JTextPane;
import java.awt.Font; 
import java.awt.GridLayout;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.UIManager;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.SystemColor;
import java.awt.Window;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.*;


public class ATM extends javax.swing.JFrame {
    

   

   Admin customer = new Admin();
   
    public ATM() {
        initComponents();
        setTitle("SBBL");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 645, 447);
                

    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        lblHeading2 = new javax.swing.JLabel();
        lblHeading1 = new javax.swing.JLabel();
        lblOk = new javax.swing.JLabel();
        lblWithdraw = new javax.swing.JLabel();
        lblDeposit = new javax.swing.JLabel();
        lblCheckBalance = new javax.swing.JLabel();
        lblCancel = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        lblHeading3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("Jframe"); // NOI18N
        setPreferredSize(new java.awt.Dimension(666, 343));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(null);

        panel1.setBackground(java.awt.Color.orange);
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel1.setForeground(java.awt.Color.white);
        panel1.setLayout(null);

        lblHeading2.setBackground(java.awt.Color.white);
        lblHeading2.setFont(new java.awt.Font("Noah", 1, 16)); // NOI18N
        lblHeading2.setText("Enter your Pin Number:");
        panel1.add(lblHeading2);
        lblHeading2.setBounds(120, 160, 200, 30);

        lblHeading1.setBackground(java.awt.Color.white);
        lblHeading1.setFont(new java.awt.Font("Noah", 1, 18)); // NOI18N
        lblHeading1.setText("Welcome to SBBL ");
        panel1.add(lblHeading1);
        lblHeading1.setBounds(120, 60, 310, 30);

        lblOk.setFont(new java.awt.Font("Noah", 1, 14)); // NOI18N
        lblOk.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOk.setText("Ok");
        lblOk.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblOkPropertyChange(evt);
            }
        });
        panel1.add(lblOk);
        lblOk.setBounds(460, 150, 60, 20);

        lblWithdraw.setFont(new java.awt.Font("Noah", 1, 14)); // NOI18N
        lblWithdraw.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWithdraw.setText("Withdraw");
        lblWithdraw.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblWithdrawPropertyChange(evt);
            }
        });
        panel1.add(lblWithdraw);
        lblWithdraw.setBounds(460, 30, 60, 20);

        lblDeposit.setFont(new java.awt.Font("Noah", 1, 14)); // NOI18N
        lblDeposit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeposit.setText("Deposit");
        lblDeposit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblDepositPropertyChange(evt);
            }
        });
        panel1.add(lblDeposit);
        lblDeposit.setBounds(460, 70, 60, 20);

        lblCheckBalance.setFont(new java.awt.Font("Noah", 1, 14)); // NOI18N
        lblCheckBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheckBalance.setText("Check");
        lblCheckBalance.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblCheckBalancePropertyChange(evt);
            }
        });
        panel1.add(lblCheckBalance);
        lblCheckBalance.setBounds(460, 110, 60, 20);

        lblCancel.setFont(new java.awt.Font("Noah", 1, 14)); // NOI18N
        lblCancel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCancel.setText("Cancel");
        panel1.add(lblCancel);
        lblCancel.setBounds(470, 190, 50, 20);

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });
        panel1.add(text1);
        text1.setBounds(120, 120, 180, 30);

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });
        panel1.add(text2);
        text2.setBounds(120, 190, 180, 30);

        lblHeading3.setBackground(java.awt.Color.white);
        lblHeading3.setFont(new java.awt.Font("Noah", 1, 16)); // NOI18N
        lblHeading3.setText("Enter your Account Number:");
        panel1.add(lblHeading3);
        lblHeading3.setBounds(120, 90, 200, 30);

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setBackground(java.awt.Color.orange);
        jFormattedTextField1.setBorder(null);
        jFormattedTextField1.setText("Dept. of CSE, Year 2021");
        panel1.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(70, 310, 160, 14);

        jFormattedTextField2.setEditable(false);
        jFormattedTextField2.setBackground(java.awt.Color.orange);
        jFormattedTextField2.setBorder(null);
        jFormattedTextField2.setText("Srijon Ashraf Zim");
        panel1.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(70, 270, 110, 20);

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setBackground(java.awt.Color.orange);
        jFormattedTextField3.setBorder(null);
        jFormattedTextField3.setText("Daffodil International University");
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        panel1.add(jFormattedTextField3);
        jFormattedTextField3.setBounds(70, 290, 160, 14);

        getContentPane().add(panel1);
        panel1.setBounds(10, 10, 530, 360);

        btnWithdraw.setBackground(java.awt.Color.lightGray);
        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(btnWithdraw);
        btnWithdraw.setBounds(550, 40, 73, 23);

        btnDeposit.setBackground(java.awt.Color.lightGray);
        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeposit);
        btnDeposit.setBounds(550, 80, 73, 23);

        btnCheck.setBackground(java.awt.Color.lightGray);
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheck);
        btnCheck.setBounds(550, 120, 73, 23);

        btnOK.setBackground(java.awt.Color.lightGray);
        btnOK.setText("Ok");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK);
        btnOK.setBounds(550, 160, 73, 23);

        btnCancel.setBackground(java.awt.Color.lightGray);
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(550, 200, 73, 23);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 270, 70, 30);

        getAccessibleContext().setAccessibleName("JFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
       
                                              
        if(!lblOk.isVisible()){ 
        lblHeading1.setText("Enter Amount to deposit: ");
        text1.setVisible (true);
        
        int c= Integer.parseInt(text1.getText());
        lblHeading1.setText("Deposited Balance: "+c);
        
        customer.setBalance(c);
        customer.sumation();
        text1.setText("");
        text1.setVisible(false);
        
        }
   
    
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
      
       if(!lblOk.isVisible())/*This means lebelOk is not visible*/{
        
        lblHeading1.setText("Remaining Balance: "+customer.getBalance());
       System.out.print("Remaining Balance:  "+customer.getBalance());
       
       text1.setVisible(false);
       }
   
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         text1.setText("");
         text2.setText("");
         lblHeading1.setText("Welcome to SBBL");
         lblHeading3.setText("Enter your Account Number:");
         lblHeading2.setText("Enter your Pin Number:");
         
         lblHeading1.setVisible(true);
         lblHeading3.setVisible(true);
         lblHeading2.setVisible(true);
         
         text1.setVisible(true);
         text2.setVisible(true);
         customer.reset();
         lblWithdraw.setVisible(false);
	 lblDeposit.setVisible(false);
	 lblCheckBalance.setVisible(false);
         btnCheck.setVisible(false);
         btnDeposit.setVisible(false);
         btnWithdraw.setVisible(false);
         lblOk.setVisible(true);
         btnOK.setEnabled(true);
         btnOK.setText("Ok");
         
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
   
        int a= Integer.parseInt(text1.getText());
        int b= Integer.parseInt(text2.getText());
        

        if (a == customer.rightAcNumber && b == customer.rightAcPin) {

					
						System.out.println("Login Sucessful!");
                                                JOptionPane.showMessageDialog(null, "Login Successful!");
                                                
                                                lblHeading1.setText("Enter the buttons to execute.");
                                                lblHeading2.setVisible(false);
                                                lblHeading3.setVisible(false);
                                                text1.setVisible(false);
                                                text2.setVisible(false);
						lblWithdraw.setVisible(true);
						lblDeposit.setVisible(true);
						lblCheckBalance.setVisible(true);
						lblOk.setVisible(false);
						lblCancel.setVisible(true);
                                                btnOK.setText("");
                                                btnOK.setEnabled(false);
                                                btnCheck.setVisible(true);
                                                btnDeposit.setVisible(true);
                                                btnWithdraw.setVisible(true);
                                                text1.setText("");
                                                text2.setText("");
                                                
                                                
                                                customer.reset();
                                                
					}
                                        

                                   
                                   else{
                                   
                                   System.out.println("Try Again!");

                                        JOptionPane.showMessageDialog(null, "Wrong informations. Try Again!");
                                        
                                        
                                        text1.setText("");
                                        text2.setText("");
                                   
                                   
                                   }

          
            
				
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void lblOkPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblOkPropertyChange
        lblOk.setVisible(true);
    }//GEN-LAST:event_lblOkPropertyChange

    private void lblCheckBalancePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblCheckBalancePropertyChange
        lblCheckBalance.setVisible(false);
    }//GEN-LAST:event_lblCheckBalancePropertyChange

    private void lblDepositPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblDepositPropertyChange
       lblDeposit.setVisible(false);
    }//GEN-LAST:event_lblDepositPropertyChange

    private void lblWithdrawPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblWithdrawPropertyChange
       lblWithdraw.setVisible(false);
    }//GEN-LAST:event_lblWithdrawPropertyChange

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        
    }//GEN-LAST:event_formPropertyChange

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
                                             
        if(!lblOk.isVisible()){ 
            
           
        lblHeading1.setText("Enter Amount to withdraw: ");
        text1.setVisible (true);
        
        int d= Integer.parseInt(text1.getText());
         if(d<=customer.getBalance()){
        lblHeading1.setText("Please Collect Your Cash: "+d);
        
        customer.setBalance(d);
        customer.minus();
        text1.setText("");
        text1.setVisible(false);
        
        }
         else{
             lblHeading1.setText("Limit exceed. Try again!");
             text1.setText("");
         }
         }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    public static void main(String args[]) {
        try {
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch (Throwable e) {
			e.printStackTrace();
		}
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					ATM frame = new ATM();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblCheckBalance;
    private javax.swing.JLabel lblDeposit;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblHeading3;
    private javax.swing.JLabel lblOk;
    private javax.swing.JLabel lblWithdraw;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}


//Srijon Ashraf